ALTER SESSION SET PLSQL_WARNINGS = 'ENABLE:ALL';

ALTER SESSION SET PLSQL_CODE_TYPE = NATIVE;
/
ALTER SESSION SET PLSQL_OPTIMIZE_LEVEL = 3;
/

CREATE OR REPLACE PACKAGE BODY bmap_operator AS

  FUNCTION bit_and(
    left IN BMAP_LEVEL_LIST,
    right IN BMAP_LEVEL_LIST
  ) RETURN BMAP_LEVEL_LIST IS
    result_bmap BMAP_LEVEL_LIST := BMAP_LEVEL_LIST();
    BEGIN
      RETURN result_bmap;
    END bit_and;

END bmap_operator;
/

SHOW ERRORS
/
