ALTER SESSION SET PLSQL_WARNINGS='ENABLE:ALL';

ALTER SESSION SET PLSQL_CODE_TYPE=NATIVE;
/
ALTER SESSION SET PLSQL_OPTIMIZE_LEVEL=3;
/

CREATE OR REPLACE PACKAGE MAPPING_UTIL AS
  FUNCTION getBitNo(
    pt_key_list MAPPING_KEY_LIST
  ) RETURN INTEGER;
END MAPPING_UTIL;
/

