BEGIN EXECUTE IMMEDIATE 'DROP TABLE employees'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE likes'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE like_seq'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE employees_likes'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

DEF NUMBER_OF_LIKES = 40000;
DEF MIN_NUMBER_OF_LIKES_FOR_EMP = 40000;

@@employees_sample.sql
@@likes_sample.sql
@@employees_likes_sample.sql

UNDEF NUMBER_OF_LIKES;
UNDEF MIN_NUMBER_OF_LIKES_FOR_EMP;
